/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Lezalit (https://sketchfab.com/Lezalit)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-smg-gun-free-442999342f5045948572441e3a29d12f
Title: SCI-FI SMG GUN - FREE
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/subgun/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-484.665, -133.898, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Plane010_Material1_0.geometry} material={materials.Material1} />
          <mesh geometry={nodes.Slice002_Material1_0.geometry} material={materials.Material1} />
        </group>
        <group position={[-484.665, -133.898, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
          <mesh geometry={nodes.Plane011_Material1_0.geometry} material={materials.Material1} />
          <mesh geometry={nodes.Slice003_Material1_0.geometry} material={materials.Material1} />
        </group>
        <mesh geometry={nodes.Rope001__0.geometry} material={materials['Rope.001__0']} position={[-2271.849, -1104.887, -127.005]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube043_Material1_0.geometry} material={materials.Material1} position={[-484.665, -133.898, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cylinder008_Material1_0.geometry} material={materials.Material1} position={[-456.747, 355.172, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube044_Material1_0.geometry} material={materials.Material1} position={[881.22, -332.139, -120.584]} rotation={[-Math.PI / 2, -0.215, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cylinder009_Material1_0.geometry} material={materials.Material1} position={[-1303.415, -272.698, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube045_Material1_0.geometry} material={materials.Material1} position={[-484.665, -133.898, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Plane013_Material1_0.geometry} material={materials.Material1} position={[-1303.415, -272.698, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube046_Material1_0.geometry} material={materials.Material1} position={[-484.665, -133.898, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Plane014_Material1_0.geometry} material={materials.Material1} position={[-1303.415, -272.698, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube047_Material1_0.geometry} material={materials.Material1} position={[-484.665, -133.898, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cylinder010_Material1_0.geometry} material={materials.Material1} position={[2324.964, 163.862, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube048_Material1_0.geometry} material={materials.Material1} position={[2642.84, 163.862, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cylinder011_Material1_0.geometry} material={materials.Material1} position={[1941.434, 10.645, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube049_Material1_0.geometry} material={materials.Material1} position={[240.026, -1055.686, -129.792]} rotation={[-Math.PI / 2, 0.353, -Math.PI / 2]} scale={[91.663, 109.645, 109.645]} />
        <mesh geometry={nodes.Cube050_Material1_0.geometry} material={materials.Material1} position={[2817.387, -147.567, -122.635]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube051_Material1_0.geometry} material={materials.Material1} position={[2741.802, 313.468, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cylinder012_Material1_0.geometry} material={materials.Material1} position={[2715.885, 313.468, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube052_Material1_0.geometry} material={materials.Material1} position={[51.982, 313.468, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Plane015_Material1_0.geometry} material={materials.Material1} position={[-1310.641, -272.698, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube053_Material1_0.geometry} material={materials.Material1} position={[-575.489, -133.898, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Plane016_Material1_0.geometry} material={materials.Material1} position={[-575.489, -133.898, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube054_Material1_0.geometry} material={materials.Material1} position={[2228.05, 163.862, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube055_Material1_0.geometry} material={materials.Material1} position={[-914.563, 88.073, -131.332]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube056_Material1_0.geometry} material={materials.Material1} position={[-874.793, -14.765, -131.331]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube057_Material1_0.geometry} material={materials.Material1} position={[51.982, 373.738, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Plane017_Material1_0.geometry} material={materials.Material1} position={[-484.665, -133.898, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube058_Material1_0.geometry} material={materials.Material1} position={[-1303.415, 205.088, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube059_Material1_0.geometry} material={materials.Material1} position={[-1303.415, 663.847, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube060_Material1_0.geometry} material={materials.Material1} position={[-1303.415, -272.698, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube061_Material1_0.geometry} material={materials.Material1} position={[-1303.415, -272.698, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube062_Material1_0.geometry} material={materials.Material1} position={[463.664, 500.389, -127.006]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube063_Material1_0.geometry} material={materials.Material1} position={[463.664, 500.389, -127.006]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube064_Material1_0.geometry} material={materials.Material1} position={[451.208, 643.225, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube065_Material1_0.geometry} material={materials.Material1} position={[2228.05, 163.862, -127.006]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Cube066_Material1_0.geometry} material={materials.Material1} position={[463.664, 500.389, -127.006]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
        <mesh geometry={nodes.Plane018_Material1_0.geometry} material={materials.Material1} position={[-497.445, 372.314, -127.006]} rotation={[-Math.PI / 2, -0.82, -Math.PI / 2]} scale={98.673} />
        <mesh geometry={nodes.Cube067_Material1_0.geometry} material={materials.Material1} position={[612.475, 500.389, -127.006]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
